@startuml
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12
start
:User executes add command;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([command successful])
else ([command
unsuccessful])
    :Error messages;
    :Edit input according to
    error messages;
endif
    :Successfully saves new
    contact to ClinicMate;
stop
@enduml
