@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":AddNoteCommandParser" as AddNoteCommandParser LOGIC_COLOR
participant "i:IdentityCardNumberMatchesPredicate" as IdentityCardNumberPredicate LOGIC_COLOR
participant "n:Note" as Note LOGIC_COLOR
participant "a:AddNoteCommand" as AddNoteCommand LOGIC_COLOR
participant "p:Person" as Person LOGIC_COLOR
participant "r:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "m:Model" as Model MODEL_COLOR
end box

note left of LogicManager
  In the diagram, params refers to the following:
  "T0123456A n\Covid"
end note

[-> LogicManager : execute("addnote params")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("addnote params")
activate AddressBookParser

create AddNoteCommandParser
AddressBookParser -> AddNoteCommandParser
activate AddNoteCommandParser

AddNoteCommandParser --> AddressBookParser
deactivate AddNoteCommandParser

AddressBookParser -> AddNoteCommandParser : parse("params")
activate AddNoteCommandParser

create IdentityCardNumberPredicate
AddNoteCommandParser -> IdentityCardNumberPredicate:
activate IdentityCardNumberPredicate

IdentityCardNumberPredicate --> AddNoteCommandParser
deactivate IdentityCardNumberPredicate

create Note
AddNoteCommandParser -> Note:
activate Note

Note --> AddNoteCommandParser
deactivate Note

create AddNoteCommand
AddNoteCommandParser -> AddNoteCommand : new AddNoteCommand(i, n, false)
activate AddNoteCommand

AddNoteCommand --> AddNoteCommandParser : a
deactivate AddNoteCommand

AddNoteCommandParser --> AddressBookParser : a
deactivate AddNoteCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
AddNoteCommandParser -[hidden]-> AddressBookParser
destroy AddNoteCommandParser

AddressBookParser --> LogicManager : a
deactivate AddressBookParser

LogicManager -> AddNoteCommand : execute(m)
activate AddNoteCommand

create Person
AddNoteCommand -> Person:
activate Person

Person --> AddNoteCommand
deactivate Person

AddNoteCommand -> Model : getPersonIfExists(...)
activate Model

Model --> AddNoteCommand
deactivate Model

AddNoteCommand -> Model : setPerson(...)
activate Model

Model --> AddNoteCommand
deactivate Model

AddNoteCommand -> Model : isPersonDisplayed(...)
activate Model

Model --> AddNoteCommand
deactivate Model

AddNoteCommand -> Model : setDisplayedNote(...)
activate Model

Model --> AddNoteCommand
deactivate Model

create CommandResult
AddNoteCommand -> CommandResult
activate CommandResult

CommandResult --> AddNoteCommand
deactivate CommandResult

AddNoteCommand --> LogicManager : r
deactivate AddNoteCommand

'Hidden arrow to position the destroy marker below the end of the activation bar.
AddNoteCommand -[hidden]-> LogicManager
destroy AddNoteCommand

[<--LogicManager
deactivate LogicManager
@enduml
