@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":EditCommandParser" as EditCommandParser LOGIC_COLOR
participant "i:IdentityCardNumberMatchesPredicate" as IdentityCardNumberPredicate LOGIC_COLOR
participant "d:EditPersonDescriptor" as EditPersonDescriptor LOGIC_COLOR
participant "e:EditCommand" as EditCommand LOGIC_COLOR
participant "r:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "m:Model" as Model MODEL_COLOR
end box

note left of LogicManager
  In the diagram, params refers to the following:
  "T0123456A p\23456789"
end note

[-> LogicManager : execute("edit params")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("edit params")
activate AddressBookParser

create EditCommandParser
AddressBookParser -> EditCommandParser
activate EditCommandParser

EditCommandParser --> AddressBookParser
deactivate EditCommandParser

AddressBookParser -> EditCommandParser : parse("params")
activate EditCommandParser

create IdentityCardNumberPredicate
EditCommandParser -> IdentityCardNumberPredicate:
activate IdentityCardNumberPredicate

IdentityCardNumberPredicate --> EditCommandParser
deactivate IdentityCardNumberPredicate

create EditPersonDescriptor
EditCommandParser -> EditPersonDescriptor:
activate EditPersonDescriptor

EditPersonDescriptor --> EditCommandParser
deactivate EditPersonDescriptor

create EditCommand
EditCommandParser -> EditCommand : new EditCommand(i, d)
activate EditCommand

EditCommand --> EditCommandParser : e
deactivate EditCommand

EditCommandParser --> AddressBookParser : e
deactivate EditCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
EditCommandParser -[hidden]-> AddressBookParser
destroy EditCommandParser

AddressBookParser --> LogicManager : e
deactivate AddressBookParser

LogicManager -> EditCommand : execute(m)
activate EditCommand

EditCommand -> Model : getPersonIfExists(...)
activate Model

Model --> EditCommand
deactivate Model

EditCommand -> Model : hasPerson(...)
activate Model

Model --> EditCommand
deactivate Model

EditCommand -> Model : setPerson(...)
activate Model

Model --> EditCommand
deactivate Model

EditCommand -> Model : updateFilteredPersonList(...)
activate Model

Model --> EditCommand
deactivate Model

create CommandResult
EditCommand -> CommandResult
activate CommandResult

CommandResult --> EditCommand
deactivate CommandResult

EditCommand --> LogicManager : r
deactivate EditCommand

'Hidden arrow to position the destroy marker below the end of the activation bar.
EditCommand -[hidden]-> LogicManager
destroy EditCommand

[<--LogicManager
deactivate LogicManager
@enduml
