@startuml
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12
start
:User executes add command;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([user input is valid])
    if () then ([patient already exists])
        :System displays patient
        already exists error message;
    else ([else])
        :System inserts patient to
        list of patients;
        :System displays added patient
        in patient list panel;
    endif
else ([else])
    :System displays specific
    error message;
endif
stop
@enduml
